const ERegion = [
  'GUADELOUPE',
  'MARTINIQUE',
  'GUYANE',
  'LA_REUNION',
  'MAYOTTE',
  'ILE_DE_FRANCE',
  'CENTRE_VAL_DE_LOIRE',
  'BOURGOGNE_FRANCHE_COMTE',
  'NORMANDIE',
  'HAUTS_DE_FRANCE',
  'GRANR_EST',
  'PAYS_DE_LA_LOIRE',
  'BRETAGNE',
  'NOUVELLE_AQUITAINE',
  'OCCITANIE',
  'AUVERGNE_RHONE_ALPES',
  'PROVENCE_ALPES_COTE_D_AZUR',
  'CORSE',
];

module.exports = ERegion;
