module.exports = {
  Club: require('./Club'),
  ClubRaw: require('./ClubRaw'),
  Course: require('./Course'),
  CourseRaw: require('./CourseRaw'),
  StatsClub: require('./StatsClub'),
  StatsCountry: require('./StatsCountry'),
  StatsDepartement: require('./StatsDepartement'),
  StatsRegion: require('./StatsRegion'),
  Swimmer: require('./Swimmer'),
  SwimmerMarge: require('./SwimmerMarge'),
  SwimmerRecord: require('./SwimmerRecord'),
  User: require('./User'),
  Session: require('./Session'),
  Preference: require('./Preference'),
};
